name: Universal Jar

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :abcdecoder:packageReleaseUberJarForCurrentOS -Puniversal

      - name: List generated files
        run: ls -R abcdecoder/build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: universal-jar
          path: abcdecoder/build/compose/jars/*.jar
